[package]
name = "oasis-amqp"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan.ochtman@ing.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
err-derive = "0.2"
serde = { version = "1", features = ["derive"] }
serde_bytes = { version = "0.11" }
oasis-amqp-derive = { version = "0.1", path = "../oasis-amqp-derive" }

[dev-dependencies]
tokio = { version = "0.2", features = ["tcp"] }
