[package]
name = "oasis-amqp"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan.ochtman@ing.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5"
err-derive = "0.2"
oasis-amqp-derive = { version = "0.1", path = "../oasis-amqp-derive" }
serde = { version = "1", features = ["derive"] }
serde_bytes = { version = "0.11" }
tokio-util = { version = "0.2", features = ["codec"] }
